apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.110.148.105
  environments:
  - key: dev
    owner: fpga-tom
    repository: jenkins-x
  - key: staging
  - key: production
  ingress:
    domain: fab2-46-34-227-192.ngrok-free.app
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: fpga-tom
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
